# Generated by Django 4.1.7 on 2023-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default=11, max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
